server:
  port: 8087

spring:
  application:
    name: notification-service

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 521c4c12434e4d
    password: 098bd92a7f6d81
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificationService
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
       schema.registry.url: http://localhost:8081


  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  observation:
    key-values:
      application: product-service
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true  # Enable histogram for these metrics
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

loki:
  url: http://localhost:3100/loki/api/v1/push
