server:
  port: 8087

spring:
  application:
    name: notification-service

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 521c4c12434e4d
    password: 098bd92a7f6d81
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificationService
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping:
                event: com.robin.microservices.order_service.event.OrderPlacedEvent

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
