version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-product-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Adewole171200
      MYSQL_DATABASE: product_service_schema
    ports:
      - "3307:3306"  # external:internal (map host port 3307 to container port 3306)
    networks:
      - microservice-net   # <-- notice the dash (-)

networks:
  microservice-net:
    driver: bridge         # <-- proper indentation
